In [12]:
import numpy as np

list_ = ['1','2','3','4','5']

array_list = np.array(object = list_)
array_list
# list_

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [52]:
#q1
print(type(array_list))
print(type(list_))

<class 'numpy.ndarray'>
<class 'list'>


In [58]:
#q2
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [56]:
for i in list_: # List_ has data type string
  print(type(i))  

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [60]:
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

In [62]:
#q3
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


After this modification, the elements in the array_list will turn to 'INT32' datatype but the data type of the list_ elements will remain same as Strings.

In [69]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
#q4
num_array.shape # Returns the Dimension of the Array

(2, 3)

In [89]:
num_array.size # Returns the number of elements in the array

6

In [91]:
#q5
zero_array = np.zeros((3,3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
zero_array.shape

(3, 3)

In [95]:
zero_array.size

9

In [ ]:
#q6
